version: '3.9'
services:
  ngx-admin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4201:4201"
    container_name: ngx-admin
    volumes:
      - ./:/app
      - /app/node_modules
